online_member_dir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include

urlpatterns = [
    path('', views.home, name='home'),
    path('import', views.importFile, name = 'import-page'),
    path('export', views.exportFile, name = 'export-page'),
    path('usa_regionsmap', views.getUSARegionsMap, name ='usa_regionsmap'),
    path('user', views.showUserProfile, name = 'user-page'),
    path('national-officers', views.getAllNationalOfficers, name = 'national-officers-page'),
    path('regional-officers', views.getAllRegionalOfficers, name = 'regional-officers-page'),
    path('center-officers', views.getAllCenterOfficers, name = 'center-officers-page'),
    path('search_members', views.search_members, name = 'search-members'),
    path('region_role/<int:regionId>', views.getRegionOfficers, name = 'region-page'),
    path('center_role/<int:centerId>', views.getCenterOfficers, name = 'center-page'),
    path('getCenterOfficers/<int:centerId>', views.getCenterOfficers, name = 'centerOfficers'),
    path('getRegionalCenters/<int:regionId>', views.getRegionalCenters, name = 'regionalCenters'),
    path('uploadFile', views.uploadFile, name = 'uploadFile'),
    path('region/<int:regionId>/centers', views.displayRegionCenters, name= 'region-centers'),
    path('contactus', views.contactus, name = 'contactus'),
    path('center/<int:centerId>/members', views.getMembersForCenter, name= 'center-members'),
    path('getMemberData/', views.getMemberData, name='memberData'),
    path('updateMemberProfile/', views.updateMemberProfile, name='updateMemberProfile'),
    path('updateMemberStatus/', views.updateMemberStatus, name='updateMemberStatus'),
    path('enableNotification/', views.enableNotification, name='enableNotification'),
]

urlpatterns += [
    url(r'^swingtime/', include('swingtime.urls')),
]

website/models.py
from django.db import models
from django.core.cache import cache
from random import randint

class Quotes(models.Model):
    #Fields
    message = models.CharField(max_length=600, help_text='Swamis Quotes')
    cite = models.CharField(max_length=100, default= "Citation")

    def __str__(self):
        return f'{self.message} || {self.cite}'

        #override save Method
    def save(self, *args, **kwargs):
        if cache.get("random_quote"):
            quotes_count = Quotes.objects.count()
            if quotes_count > 0:
                random_quote = Quotes.objects.all()[randint(0, quotes_count - 1)]
                cache.set("quotes_count", quotes_count)
                cache.set("random_quote", random_quote)
        super(Quotes, self).save(*args, **kwargs)

class Region(models.Model):

    # Fields
    name = models.CharField(max_length=20, help_text='Region Name')
    notification = models.BooleanField(default=False)

    # Metadata
    # this metadata is to control the default ordering of records returned when you query the model type
    #ordering = ['name']

    # Methods

    def __str__(self):
        return self.name

    #override save Method
    def save(self, *args, **kwargs):
        if cache.get("member_regions"):
            mem_regions = Region.objects.all()
            cache.set("member_regions", mem_regions)
        super(Region, self).save(*args, **kwargs)


class Center(models.Model):

    # Fields
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive')
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, help_text='Center Status', default = 'Active')
    CENTER_GROUP = [
        ('Center', 'Center'),
        ('Group', 'Group')
    ]
    center_type = models.CharField(max_length=10, choices=CENTER_GROUP, help_text='Center centerType', default = 'Center')
    name = models.CharField(max_length=100, help_text='Center Name')
    address = models.CharField(max_length=100, help_text='Center Address', null=True, blank=True)
    city = models.CharField(max_length=60, help_text='Center City', null=True, blank=True)
    state = models.CharField(max_length=30, help_text='Center State', null=True,blank=True)
    zip_code = models.CharField(max_length=10,help_text='Center Zip', null=True, blank=True)
    country = models.CharField(max_length=30, help_text='Center Country', default = 'USA')
    phone = models.BigIntegerField(help_text='Center Phone', default=0)
    website = models.URLField(help_text='Center website', null=True, blank=True)
    latitude=models.DecimalField(max_digits=30, decimal_places=6,help_text='Center Latitude', default = 0.0)
    longitude=models.DecimalField(max_digits=30, decimal_places=6,help_text='Center Longitude', default = 0.0)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    # metadata
    #ordering = ['name']

    # Methods
    def __str__(self):
        return self.name


class OrgRole(models.Model):

    #Fields
    name = models.CharField(max_length=100, help_text='Organization Role Name')
    description = models.CharField(
        max_length=200, help_text='Organization Role Description', blank=True)

    # metadata
    ordering = ['name']

    # Methods
    def __str__(self):
        return self.name

    #override save Method
    def save(self, *args, **kwargs):
        mem_roles = OrgRole.objects.all()
        cache.set("member_orgroles", mem_roles)
        super(OrgRole, self).save(*args, **kwargs)


class AppRole(models.Model):

    # Fields
    name = models.CharField(max_length=100, help_text='Application Role Name')
    level = models.CharField(
        max_length=2, help_text='access level', default="L1")
    description = models.CharField(
        max_length=200, help_text='Application Role Description', blank=True)

    # metadata
    ordering = ['name']

    # Methods
    def __str__(self):
        return self.name


class Metadata(models.Model):
    key = models.CharField(max_length=100, primary_key=True)
    value = models.CharField(max_length=600)

    def __str__(self):
        return f'{self. key} | {self.value}'


class Member(models.Model):

    # Fields
    first_name = models.CharField(
        max_length=100, help_text='Member First Name')
    last_name = models.CharField(max_length=100, help_text='Member Last Name')
    GENDERCHOICES = [
        ('m', 'Male'),
        ('f', 'Female'),
        ('', 'Not Specified'),
    ]
    gender = models.CharField(max_length=1, choices=GENDERCHOICES,
                              default='', help_text='Member Gender', blank=True)
    email = models.EmailField(
        max_length=30, help_text='Member Email', primary_key=True, null=False)
    phone = models.CharField(max_length=15, help_text='Member Phone', blank=True)
    address_1 = models.CharField(
        max_length=150, help_text='Member Address_1', null=True, blank=True)
    address_2 = models.CharField(
        max_length=150, help_text='Member Address_2', null=True, blank=True)
    city = models.CharField(max_length=60, help_text='Member City', blank=True)
    zip_code = models.CharField(
        max_length=10, help_text='Member zip_code', null=True, blank=True)
    state = models.CharField(max_length=30, help_text='Member state')
    country = models.CharField(
        max_length=30, help_text='Member country', default='USA')
    AGEGROUPCHOICES = [
        ('SSE', 'SSE (4 - 18)'),
        ('YA', 'YA (18 - 40)'),
        ('Adult', 'Adult (40 +)'),
        ('', 'Not Specified'),
    ]
    age_group = models.CharField(
        max_length=10, choices=AGEGROUPCHOICES, default='', blank=True)
    MEMBERCHOICES = [
        (0, 'Pending_Approval'),
        (1, 'Approved'),
    ]
    member_status = models.IntegerField(
        choices=MEMBERCHOICES, default=0, help_text='member status')
    orgrole = models.ManyToManyField(
        OrgRole, help_text='select organization role')
    approle = models.ForeignKey(AppRole, on_delete=models.CASCADE)
    start_date = models.DateField(
        help_text="Member's OrgRole Start Date", blank=True, null=True)
    end_date = models.DateField(
        help_text="Member's OrgRole End Date", blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    center = models.ForeignKey(Center, on_delete=models.SET_NULL, null=True)

    def get_orgrole(self):
        return " | ".join([orgtitle.name for orgtitle in self.orgrole.all()])

    get_orgrole.short_description = 'Org Title'

    class Meta:
        ordering = ['first_name']
        permissions = (
            ("is_central_officer", "is central officer"),
            ("is_regional_officer", "is regional officer"),
            ("is_national_officer", "is national officer"),
            #("can_modify_member_data", "to modify member data"),
        )

website/forms.py
from django import forms
from django.forms import ModelForm,TextInput, EmailInput,NumberInput,HiddenInput
from .models import Member

# creating a form
class UserProfileForm(ModelForm):
    class Meta:
        model = Member
        fields = ["first_name", "last_name", "phone", "address_1", "city", "state", "email","zip_code", "age_group"]

        help_texts = {
            'first_name': None,
            'last_name': None,
            'phone': None,
            'address_1': None,
            'city': None,
            'state': None,
            'zip_code': None,
            'email': None,
            'age_group': None
        }

        widgets = {
            'first_name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your First Name'
                }),
            'last_name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your First Name'
                }),
            'phone': NumberInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your Phone Number'}),

            'address_1': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your Address'
                }),
            'city': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your City'
                }),
            'state':TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your State'
                }),
            'zip_code':TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your ZipCode'
                }),
            'age_group':forms.Select(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Enter your ZipCode'
                }),
            'email':HiddenInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px; display: none',
                })
            }

website/templates/ack.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron text-center">
  <h1 class="display-3">Thank You for reaching out!</h1>
  <p class="lead"><strong>We have received your message and we will reach out to you as soon as possible.</p>
  <hr>
</div>
{% endblock content %}

website/templates/auth.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  {% if message %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
  {% endif %}


  <div class="card mx-auto mt-5" style="max-width: 36rem;">
  <div class="card-header"><h3 class="card-title text-primary" style="font-family: 'Supermercado One', cursive;">Portal Login</h3></div>
  <div class="card-body">

    <div class="bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        Stage One - Generate and receive code to your email
      </h6>
      <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 small lh-125">
          <form action="{% url 'home' %}" method="POST">
            {% csrf_token %}
            <div class="row form-row">
              <div class="col-md-7">
                {% if issued %}
                  <input disabled type="text" required class="form-control" name="emailaddress" id="emailaddress" value="{{ email }}">
                {% else %}
                  <input type="text" required class="form-control" name="emailaddress" id="emailaddress" placeholder="Enter your email address">
                {% endif %}
              </div>
              <div class="col-md-5">
                {% if issued %}
                  <button disabled type="submit" class="btn btn-secondary" style="font-family: 'Supermercado One', cursive;">Generate Code</button>
                {% else %}
                  <button type="submit" class="btn btn-secondary" style="font-family: 'Supermercado One', cursive;">Generate Code</button>
                {% endif %}
              </div>
            </div>
          </form>
        </p>
      </div>
      <br/>
      <h6 class="border-bottom border-gray pb-2 mb-0">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#FFA500"/><text x="50%" y="50%" fill="#FFA500" dy=".3em">32x32</text></svg>
        Stage Two - Submit received code from email to proceed
      </h6>
      <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 small lh-125">
          <form action="{% url 'home' %}" method="POST">
            {% csrf_token %}
            <div class="row form-row">
              <div class="col-md-7">
                {% if issued %}
                  <input type="text" required class="form-control" name="authcode" id="authcode" placeholder="Enter Auth code">
                {% else %}
                  <input disabled type="text" required class="form-control" name="authcode" id="authcode" placeholder="Enter Auth code">
                {% endif %}
              </div>
              <div class="col-md-5">
                {% if issued %}
                  <input type="hidden" name="email" value="{{ email }}"/>
                  <button type="submit" class="btn btn-secondary" style="font-family: 'Supermercado One', cursive;">Authenticate</button>
                {% else %}
                  <button disabled type="submit" class="btn btn-secondary" style="font-family: 'Supermercado One', cursive;">Authenticate</button>
                {% endif %}
              </div>
            </div>
          </form>
        </p>
      </div>
    </div>

  </div>
  </div>
{% endblock content %}

website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Supermercado+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=League+Gothic&family=Titillium+Web:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@100;200&family=Nunito+Sans:wght@200;300&family=Smooch+Sans:wght@100;400;500;700&display=swap" rel="stylesheet">

    <!--For USA Regions Map tooltips -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/tooltipster@4.2.5/dist/css/plugins/tooltipster/sideTip/themes/tooltipster-sideTip-borderless.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/tooltipster@4.2.5/dist/css/tooltipster.bundle.min.css"
    />

    <title>SSIO-Member-Portal</title>
    <!-- Custome CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  </head>

  <body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}
    <div class="container-fluid mt-3">
      <div class="row">
        <div class="col-xs-9" style="flex: 1">
          {% block content %} {% endblock content %}
        </div>
      </div>
    </div>
    <br />
    {% include 'footer.html' %}
    <!--Option 2: Separate Popper and Bootstrap JS -->

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous">
    </script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>

    <script>
      var csrftoken = '{{ csrf_token }}';
    </script>

    <!-- This is for USARegions Map -->

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tooltipster@4.2.5/dist/js/tooltipster.bundle.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </body>
</html>

website/templates/display-all-centers.html
{% extends 'base.html' %}
{% block content %}
	<nav class="nav nav-pills nav-fill">
		<a class="nav-link" aria-current="page" href="{% url 'region-page' regionId %}">Regional Officers</a>
		<a class="nav-link active" href="{% url 'region-centers' regionId %}">Show Centers</a>
	</nav>

	<div class="mt-3">
		<div class="container">
			<div class="region-center-intro">
			<h1 class="text-center officers-page-title">Centers from {{ regionName}} </h1>
			</div>
		</div>

		<center>
			<table class="table">
				<tr>
				<th scope="col">Center Name</th>
				<th scope="col">Center Type</th>
				<th scope="col">City</th>
				<th scope="col">State</th>
				<th scope="col">Zipcode</th>
				<th scope="col">Website</th>
				</tr>
				{% for center in centersByRegionId %}
				<tr>
				<td><a href="{% url 'center-page' center.id %}">{{ center.name}}</a></td>
				<td>{{ center.center_type}}</td>
				<td>{{ center.city}}</td>
				<td>{{ center.state}}</td>
				<td>{{ center.zip_code}}</td>
				<td>
					<a href="{{ center.website }}" target="_blank">{{ center.website }}</a>
				</td>
				</tr>
				{% endfor %}
			</table>
		</center>
	</div>
{% endblock %}

website/templates/filter-list.html
{% extends 'base.html' %} {% load static %}{% block content %}
<br />
<br />
<div class="container">
  <form method="get">
    {{ filtered_persons.form }}
    <input type="submit" value="Search" name="" />
  </form>
  <br />
  <br />
  <table class="table">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Gender</th>
    </tr>
    {% for person in filtered_persons.qs %}
    <tr>
      <td>{{ person.first_name }}</td>
      <td>{{ person.last_name }}</td>
      <td>{{ person.gender }}</td>
    </tr>
    {% endfor %}
  </table>

  <br />

  <br />
</div>
{% endblock content %}

website/templates/findsai-centers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header class="outer-header">
  <h1 class="inner-title">Find Sai Centers</h1>
</header>

<div class="container">
  <h1>This is where to embed the prolo div script tage</h1>
</div>




{% endblock %}

website/templates/show-officers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="empty">

</div>
<div class="container-fluid">

  <div class="row">
    <div class="col-1">
      <div class="form-check">
        {% if gridcheckflag %}
          <input class="form-check-input" type="checkbox" id="gridCheck" onclick="displayFilter();" checked>
        {% else %}
          <input class="form-check-input" type="checkbox" id="gridCheck" onclick="displayFilter();">
        {% endif %}
        <label class="form-check-label" for="gridCheck" style="font-size: x-small">
          Show Filter
        </label>
      </div>
    </div>
    <div class="col-11 text-center">
      <h3>{{ officer_header }}</h3>
    </div>
  </div>
  <div class="empty">

  </div>

  <div class="row ml-auto">
    {% if gridcheckflag %}
      <div id="datafilter" class="col-3" style="border-right: 1px dashed #333;width:18%">
    {% else %}
      <div id="datafilter" class="col-3 d-none" style="border-right: 1px dashed #333;width:18%">
    {% endif %}
      <form method="get" class="mt-3">
          <div class="form-row">
            <div class="form-group col">
              <label class="form-label" for="id_first_name">First name contains:</label>
              <input type="text" name="first_name" id="id_first_name" placeholder="First Name">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-auto">
              <label class="form-label" for="id_center__name">Center name contains:</label>
              <input type="text" name="center__name" id="id_center__name" placeholder="Center Name">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-auto">
              <label class="form-label" for="id_orgrole__name">Orgrole name contains:</label>
              <select name="orgrole" id="id_orgrole" multiple="">
                  {% for member_or in member_orgroles %}
                    <option value="{{member_or.id}}">{{member_or.name}}</option>
                  {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col mt-3">
              <label class="form-label" for="id_region">Region:</label>
              <select name="region" id="id_region">
                {% for member_region in member_regions %}
                  {% if forloop.counter == 1 %}
                    <option value="" selected>All</option>
                  {% endif %}
                  <option value="{{member_region.id}}">{{member_region.name}}</option>
                {% endfor %}
              </select>
            </div>
          <div class="form-row">
            <div class="form-group col mt-3">
              <label class="form-label" for="id_member_status">Member status:</label>
              <select name="member_status" id="id_member_status">
                <option value="" selected="selected">All</option>

                <option value="0">Pending_Approval</option>

                <option value="1">Approved</option>

              </select>
            </div>
          </div>
          </div>
        <input type="hidden" name="gridcheckflag" id="gridcheckflag" value="true"/>
        <button class="btn btn-primary mt-3" type="submit">Apply Filter</button>
      </form>
    </div>

    <!-- Modal -->

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" data-bs-toggle="staticModel" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Edit Member Profile</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <table class="table table-striped">
              <tr>
                <th>First Name</th>
                <td><input type="text" id="first_name" value=""/></td>
              </tr>
              <tr>
                <th>Last Name</th>
                <td><input type="text" id="last_name" value=""/></td>
              </tr>
              <tr>
                <th>Email Address</th>
                <td id="emailaddr"></td>
              </tr>
              <tr>
                <th>Organization Role</th>
                <td>
                  <select name="orgrole" id="m_id_orgrole" multiple="">
                    {% for member_or in member_orgroles %}
                      <option value="{{member_or.id}}">{{member_or.name}}</option>
                    {% endfor %}
                  </select>
                </td>
              </tr>

              <tr>
                <th>App Role</th>
                <td>
                  <select name="approle" id="m_id_approle">
                    {% for member_ar in member_approles %}
                      <option value="{{member_ar.id}}">{{member_ar.name}}</option>
                    {% endfor %}
                  </select>
                </td>
              </tr>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="saveChanges();">Save Changes</button>
          </div>
        </div>
      </div>
    </div>

    <div class="col">
      <table class="table">
        <tr>
          <th scope="col"></th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">Email-ID</th>
          <th scope="col">Org-Role</th>
          <th scope="col">App-Role</th>
          <th scope="col">Member Status</th>
          <th scope="col">Region</th>
          <th scope="col">Center</th>
        </tr>
        {% for officer in officers_data %}
        <tr>
          <th scope="row"><img src="{% static 'images/editIcon.png' %}" classs="img-fluid" onclick="showEditUI('{{ officer.email }}');" data-bs-toggle="modal" data-bs-target="#staticBackdrop"/></th>
          <td>{{ officer.first_name}}</td>
          <td>{{ officer.last_name }}</td>
          <td>{{ officer.email }}</td>
          <td>
            {% for mem in officer.orgrole.all %}
              {% if forloop.counter == 1 %}
                {{ mem }}
              {% else %}
                | {{ mem }}
              {% endif %}
           {% endfor %}
          </td>
          <td>{{ officer.approle }}</td>
          {% if officer.member_status == 0 %}
            <td>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" onclick="setMemberStatus('{{ officer.email }}');">
                <label class="form-check-label" for="flexSwitchCheckDefault" id="{{ officer.email }}_member_status">Pending_Approval</label>
              </div>
            </td>
          {% else %}
          <td>
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked onclick="setMemberStatus('{{ officer.email }}');">
              <label class="form-check-label" for="flexSwitchCheckChecked" id="{{ officer.email }}_member_status">Approved</label>
            </div>
          </td>
          {% endif %}
          <td>
            {% if perms.website.is_central_officer and request.user.is_staff is False %}
              {{ officer.region}}
            {% else %}
            <a href="{% url 'region-page' officer.region_id %}">
              {{ officer.region}}
            </a>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'center-page' officer.center_id %}"
              >{{ officer.center }}</a
            >
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      {% if officers_data %}
        <div class="text-center mb-3">
          <span class="step-links">
              {% if officers_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ officers_data.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ officers_data.number }} of {{ officers_data.paginator.num_pages }}.
              </span>

              {% if officers_data.has_next %}
                  <a href="?page={{ officers_data.next_page_number }}">next</a>
                  <a href="?page={{ officers_data.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

website/templates/test.html
{% extends 'base.html' %} {% load static %} {% block content %}
{% endblock %}